/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.imovel.view;

import br.com.ifba.contribuinte.view.GerenciarContribuintes;
import br.com.ifba.imovel.controller.ImovelIController;
import br.com.ifba.imovel.entity.Imovel;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author eduar
 */
public class GerenciarImoveis extends javax.swing.JFrame {
    
     private static final Logger log = LoggerFactory.getLogger(GerenciarImoveis.class);

    private final ImovelIController imovelController;
    private final TelaCadastroImovel telaCadastro;
    
    /**
     * Creates new form GerenciarImoveis
     */
    public GerenciarImoveis(ImovelIController imovelController, TelaCadastroImovel telaCadastro) {
        this.imovelController = imovelController;
        this.telaCadastro = telaCadastro;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
        carregarTabela();
    }
    
    public void carregarTabela(){
        javax.swing.table.DefaultTableModel modelo = 
            (javax.swing.table.DefaultTableModel) tblImoveis.getModel();
        modelo.setRowCount(0);

        for (Imovel i : imovelController.listarTodos()) {
            // Mostrando o nome do contribuinte associado na tabela
            String nomeDono = i.getContribuinte() != null ? i.getContribuinte().getNome() : "Sem dono";
            
            modelo.addRow(new Object[]{
                i.getInscricaoImobiliaria(), 
                nomeDono, 
                i.getValorVenal(), 
                i.getId()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblImoveis = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblImoveis);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtBuscar.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblImoveis.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um imóvel na tabela para excluir.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id                 = (Long)   tblImoveis.getValueAt(linha, 3);
        String inscricao          = (String) tblImoveis.getValueAt(linha, 0);
 
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o imóvel:\n\"" + inscricao + "\"?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                imovelController.deletar(id);
                JOptionPane.showMessageDialog(this,
                        "Imóvel excluído com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblImoveis.clearSelection();
                carregarTabela();
 
            } catch (Exception ex) {
                log.error("Erro ao excluir imóvel ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tblImoveis.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um imóvel na tabela para editar.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long id = (Long) tblImoveis.getValueAt(linha, 3);
 
        // Busca o objeto completo para obter endereço e contribuinte,
        // que não estão totalmente expostos nas colunas da tabela
        Imovel imovel = imovelController.buscarPorId(id);
 
        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(imovel);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();
 
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
 
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblImoveis.getModel();
        modelo.setRowCount(0);
 
        try {
            imovelController.listarTodos().stream()
                .filter(i ->
                    i.getInscricaoImobiliaria().toLowerCase().contains(texto.toLowerCase()) ||
                    (i.getContribuinte() != null &&
                     i.getContribuinte().getNome().toLowerCase().contains(texto.toLowerCase()))
                )
                .forEach(i -> {
                    String nomeContribuinte = i.getContribuinte() != null
                            ? i.getContribuinte().getNome()
                            : "Sem contribuinte";
                    modelo.addRow(new Object[]{
                        i.getInscricaoImobiliaria(),
                        nomeContribuinte,
                        i.getValorVenal(),
                        i.getId()
                    });
                });
 
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum imóvel encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }
 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImoveis;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
