/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.imovel.view;

import br.com.ifba.contribuinte.view.GerenciarContribuintes;
import br.com.ifba.imovel.controller.ImovelIController;
import br.com.ifba.imovel.entity.Imovel;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class GerenciarImoveis extends javax.swing.JFrame {
    
     private static final Logger log = LoggerFactory.getLogger(GerenciarImoveis.class);

    private final ImovelIController imovelController;
    private final TelaCadastroImovel telaCadastro;
    
    /**
     * Creates new form GerenciarImoveis
     */
    public GerenciarImoveis(ImovelIController imovelController, TelaCadastroImovel telaCadastro) {
        this.imovelController = imovelController;
        this.telaCadastro = telaCadastro;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
        carregarTabela();
    }
    
    public void carregarTabela(){
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblImoveis.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        try {
            for (br.com.ifba.imovel.entity.Imovel i : imovelController.listarTodos()) {
                
                // 1. Verifica e pega o nome do dono
                String nomeDono;
                if (i.getContribuinte() != null) {
                    nomeDono = i.getContribuinte().getNome();
                } else {
                    nomeDono = "Sem dono";
                }
                
                // 2. Verifica e pega o bairro com segurança
                String bairro;
                if (i.getEndereco() != null && i.getEndereco().getBairro() != null) {
                    bairro = i.getEndereco().getBairro();
                } else {
                    bairro = "-";
                }
                
                // 3. Adiciona a linha na mesma ordem configurada no visual
                modelo.addRow(new Object[]{
                    i.getInscricaoImobiliaria(), // Coluna 1: Inscrição
                    nomeDono,                    // Coluna 2: Contribuinte
                    bairro,                      // Coluna 3: Bairro
                    i.getValorVenal(),           // Coluna 4: Valor Venal
                    i.getId()                    // Coluna 5: ID
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblImoveis = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Inscrição", "Contribuinte", "Bairro", "Valor Venal", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblImoveis);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar.png"))); // NOI18N
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        btnExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnEditar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblImoveis.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um imóvel na tabela para excluir.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id                 = (Long)   tblImoveis.getValueAt(linha, 4);
        String inscricao          = (String) tblImoveis.getValueAt(linha, 0);
 
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o imóvel:\n\"" + inscricao + "\"?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                imovelController.deletar(id);
                JOptionPane.showMessageDialog(this,
                        "Imóvel excluído com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblImoveis.clearSelection();
                carregarTabela();
 
            } catch (Exception ex) {
                log.error("Erro ao excluir imóvel ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tblImoveis.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,"Selecione um imóvel na tabela para editar.","Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long id = (Long) tblImoveis.getValueAt(linha, 4);
 
        // Busca o objeto completo para obter endereço e contribuinte,
        // que não estão totalmente expostos nas colunas da tabela
        Imovel imovel = imovelController.buscarPorId(id);
 
        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(imovel);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();

        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }

        javax.swing.table.DefaultTableModel modelo = 
                (javax.swing.table.DefaultTableModel) tblImoveis.getModel();
        modelo.setRowCount(0);

        try {
            // Pegamos a lista completa de imóveis (usando 'var' para inferir o tipo da sua classe)
            var listaDeImoveis = imovelController.listarTodos();

            // Substituímos o .stream().forEach() por um laço 'for' tradicional
            for (var i : listaDeImoveis) {
        
                // 1. Expandindo a lógica do .filter()
                boolean correspondeABusca = false;

                // Verifica se o texto digitado está na inscrição imobiliária
                if (i.getInscricaoImobiliaria().toLowerCase().contains(texto.toLowerCase())) {
                    correspondeABusca = true;
                }

                // Verifica se o texto digitado está no nome do contribuinte
                if (i.getContribuinte() != null) {
                    if (i.getContribuinte().getNome().toLowerCase().contains(texto.toLowerCase())) {
                        correspondeABusca = true;
                    }
                }

                // Se o imóvel bateu com alguma das condições acima, preparamos os dados
                if (correspondeABusca) {
            
                    // 2. Expandindo o ternário do Contribuinte
                    String nomeContribuinte;
                    if (i.getContribuinte() != null) {
                        nomeContribuinte = i.getContribuinte().getNome();
                    } else {
                        nomeContribuinte = "Sem contribuinte";
                    }

                    // 3. A lógica do Bairro (que já havíamos expandido)
                    String bairro;
                    if (i.getEndereco() != null) {
                        bairro = i.getEndereco().getBairro();
                    } else {
                        bairro = "-";
                    }

                    // 4. Finalmente, adicionamos a linha na tabela
                    modelo.addRow(new Object[]{
                        i.getInscricaoImobiliaria(),
                        nomeContribuinte,
                        bairro,
                        i.getValorVenal(),
                        i.getId()
                    });
                }
            }

            // Se o laço terminou e nenhuma linha foi adicionada
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum imóvel encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImoveis;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
