/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.imovel.view;
import br.com.ifba.contribuinte.controller.ContribuinteIController;
import br.com.ifba.contribuinte.entity.Contribuinte;
import br.com.ifba.contribuinte.entity.Endereco;
import br.com.ifba.imovel.controller.ImovelIController;
import br.com.ifba.imovel.entity.Imovel;
import br.com.ifba.infrastructure.util.ContribuinteItem;
import java.util.List;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaCadastroImovel extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaCadastroImovel.class); 
    private GerenciarImoveis telaPrincipal;
    private Long   idEmEdicao = null;
    private String modo       = "SALVAR";
    private final ImovelIController imovelController;
    private final ContribuinteIController contribuinteController;
    /**
     * Creates new form TelaCadastroContribuinte
     */
    public TelaCadastroImovel(ImovelIController imovelController, ContribuinteIController contribuinteController) {
        this.imovelController = imovelController;
        this.contribuinteController = contribuinteController;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    // Método para preencher o ComboBox com dados do banco
    public void carregarComboBoxContribuintes() {
        cmbContribuinte.removeAllItems(); // Limpa itens antigos
        List<Contribuinte> listaContribuintes = contribuinteController.findByAtivoTrue();
        
        for (Contribuinte c : listaContribuintes) {
            Long id = c.getId();
            String nome = c.getNome();
    
            //  o objeto que vai para o ComboBox usando essas variáveis
            ContribuinteItem item = new ContribuinteItem(id, nome);
   
            //o item pronto vai para o ComboBox
            cmbContribuinte.addItem(item);
        }
    }
    
    public void setModo(String modo, Long id, GerenciarImoveis principal) {
        this.modo = modo;
        this.idEmEdicao = id;
        this.telaPrincipal = principal;
        
        lblTitulo.setText(modo.equals("EDITAR") ? "EDITAR IMÓVEL" : "CADASTRAR IMÓVEL");
        
        // Sempre carrega o combobox quando a tela for aberta
        carregarComboBoxContribuintes();
 
        if (modo.equals("SALVAR")) {
            limparCampos();
        }
    }
    
    public void preencherCampos(Imovel i) {
        txtInscricao.setText(i.getInscricaoImobiliaria());
        txtAreaTerreno.setText(String.valueOf(i.getAreaTerreno()));
        txtAreaConstruida.setText(String.valueOf(i.getAreaConstruida()));
        txtValorVenal.setText(String.valueOf(i.getValorVenal()));
 
        // Seleciona o contribuinte dono no ComboBox pelo ID
        if (i.getContribuinte() != null) {
            for (int idx = 0; idx < cmbContribuinte.getItemCount(); idx++) {
                ContribuinteItem item = (ContribuinteItem) cmbContribuinte.getItemAt(idx);
                if (item.getId().equals(i.getContribuinte().getId())) {
                    cmbContribuinte.setSelectedIndex(idx);
                    break;
                }
            }
            
        }
 
        // Preenche os campos de endereço
        if (i.getEndereco() != null) {
            Endereco end = i.getEndereco();
            txtLogradouro.setText(end.getLogradouro());
            txtNumero.setText(end.getNumero());
            txtComplemento.setText(end.getComplemento() != null ? end.getComplemento() : "");
            txtBairro.setText(end.getBairro());
            txtCidade.setText(end.getCidade());
            cmbEstado.setSelectedItem(end.getEstado());
            txtCep.setText(end.getCep());
        }
    }

    private void limparCampos() {
        txtInscricao.setText("");
        txtAreaTerreno.setText("");
        txtAreaConstruida.setText("");
        txtValorVenal.setText("");
        txtLogradouro.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        if(cmbContribuinte.getItemCount() > 0) cmbContribuinte.setSelectedIndex(0);
        cmbEstado.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblPredios = new javax.swing.JLabel();
        lblInscricaoImobiliaria = new javax.swing.JLabel();
        lblAreaConstruida = new javax.swing.JLabel();
        lblAreaTerreno = new javax.swing.JLabel();
        lblValorVenal = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblSeta = new javax.swing.JLabel();
        txtInscricao = new javax.swing.JTextField();
        txtAreaTerreno = new javax.swing.JTextField();
        txtAreaConstruida = new javax.swing.JTextField();
        txtValorVenal = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        lblNome5 = new javax.swing.JLabel();
        lblNome6 = new javax.swing.JLabel();
        lblNome7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblContribuinte = new javax.swing.JLabel();
        cmbContribuinte = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo Automático da terceira tela");

        lblPredios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/compras.png"))); // NOI18N

        lblInscricaoImobiliaria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblInscricaoImobiliaria.setText("Inscrição Imobiliaria:");

        lblAreaConstruida.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblAreaConstruida.setText("Area Construida (m²) : ");

        lblAreaTerreno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblAreaTerreno.setText("Area do Terreno (m²):");

        lblValorVenal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblValorVenal.setText("Valor Venal (R$) : ");

        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTitulo.setText("Campos de endereço");

        lblSeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setas-flechas_1.png"))); // NOI18N

        txtInscricao.addActionListener(this::txtInscricaoActionPerformed);

        txtAreaTerreno.addActionListener(this::txtAreaTerrenoActionPerformed);

        txtAreaConstruida.addActionListener(this::txtAreaConstruidaActionPerformed);

        txtValorVenal.setEditable(false);
        txtValorVenal.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtValorVenal.setText("***AUTOMÁTICO***");
        txtValorVenal.addActionListener(this::txtValorVenalActionPerformed);

        lblNome1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome1.setText("Numero:");

        lblNome2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome2.setText("Bairro:");

        lblNome3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome3.setText("Cidade:");

        lblNome4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome4.setText("Logadouro:");

        lblNome5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome5.setText("Estado:");

        lblNome6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome6.setText("CEP:");

        lblNome7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNome7.setText("Complemento:");

        txtNumero.addActionListener(this::txtNumeroActionPerformed);

        txtLogradouro.addActionListener(this::txtLogradouroActionPerformed);

        txtBairro.addActionListener(this::txtBairroActionPerformed);

        txtCep.addActionListener(this::txtCepActionPerformed);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblContribuinte.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContribuinte.setText("Contribuinte :");

        cmbContribuinte.setModel(new javax.swing.DefaultComboBoxModel<>(new ContribuinteItem[] {}));
        cmbContribuinte.addActionListener(this::cmbContribuinteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPredios)
                .addGap(18, 18, 18)
                .addComponent(lblNome7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(lblSubTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSeta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblInscricaoImobiliaria)
                                            .addComponent(lblAreaTerreno))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAreaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(txtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorVenal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorVenal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome1)
                                    .addComponent(lblNome5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNome6)
                                            .addComponent(lblNome2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAreaConstruida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAreaConstruida, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblContribuinte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContribuinte)
                    .addComponent(cmbContribuinte, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAreaTerreno)
                                    .addComponent(txtAreaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValorVenal)
                                    .addComponent(txtValorVenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(lblSubTitulo)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSeta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome4)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome1)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNome6)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNome5)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNome3))
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome7)))
                            .addComponent(lblPredios, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInscricaoImobiliaria)
                            .addComponent(txtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAreaConstruida)
                            .addComponent(txtAreaConstruida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInscricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInscricaoActionPerformed

    private void txtAreaTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTerrenoActionPerformed

    private void txtAreaConstruidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruidaActionPerformed

    private void txtValorVenalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVenalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVenalActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar se um contribuinte foi selecionado
            ContribuinteItem itemSelecionado = (ContribuinteItem) cmbContribuinte.getSelectedItem();
            if (itemSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Por favor, selecione um contribuinte.", "Erro", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Monta o objeto Endereco
            Endereco endereco = new Endereco();
            endereco.setLogradouro(txtLogradouro.getText());
            endereco.setNumero(txtNumero.getText());
            endereco.setComplemento(txtComplemento.getText());
            endereco.setBairro(txtBairro.getText());
            endereco.setCidade(txtCidade.getText());
            endereco.setEstado((String) cmbEstado.getSelectedItem());
            endereco.setCep(txtCep.getText());
 
            // 3. Monta o objeto Imovel
            Imovel dados = new Imovel();
            dados.setInscricaoImobiliaria(txtInscricao.getText());
            dados.setEndereco(endereco);
            
            // --- INÍCIO DOS IFS EXPANDIDOS PARA CONVERSÃO DE NÚMEROS ---
            
            // Área Terreno
            if (txtAreaTerreno.getText().isEmpty()) {
                dados.setAreaTerreno(0.0);
            } else {
                dados.setAreaTerreno(Double.parseDouble(txtAreaTerreno.getText()));
            }

            // Área Construída
            if (txtAreaConstruida.getText().isEmpty()) {
                dados.setAreaConstruida(0.0);
            } else {
                dados.setAreaConstruida(Double.parseDouble(txtAreaConstruida.getText()));
            }

            // Valor Venal
            dados.setValorVenal(dados.calcularValorVenal());
            
            // --- FIM DAS CONVERSÕES ---
            
            // 4. Associa o Contribuinte ao Imóvel
            Contribuinte dono = contribuinteController.findById(itemSelecionado.getId());
            dados.setContribuinte(dono);
 
            // 5. CAIXA DE CONFIRMAÇÃO ANTES DE SALVAR COM IF/ELSE
            String mensagem;
            if (modo.equals("EDITAR")) {
                mensagem = "Tem certeza que deseja salvar as alterações neste imóvel?";
            } else {
                mensagem = "Tem certeza que deseja cadastrar este novo imóvel?";
            }
            
            int resposta = JOptionPane.showConfirmDialog(
                    this, 
                    mensagem, 
                    "Confirmar Ação", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE
            );

            // Se o usuário clicar em "Não" (NO_OPTION) ou fechar a janela, cancelamos a ação
            if (resposta != JOptionPane.YES_OPTION) {
                return; 
            }

            //  Decide entre Salvar e Atualizar
            if (modo.equals("EDITAR") && idEmEdicao != null) {
                imovelController.update(idEmEdicao, dados);
                JOptionPane.showMessageDialog(this, "Imóvel atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                imovelController.save(dados);
                JOptionPane.showMessageDialog(this, "Imóvel cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
 
            limparCampos();
            telaPrincipal.carregarTabela();
            this.dispose();
 
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Certifique-se de digitar números válidos nas áreas e valor venal.", "Erro de Digitação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            log.warn("Erro ao salvar imóvel: {}", ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogradouroActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void cmbContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContribuinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbContribuinteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<ContribuinteItem> cmbContribuinte;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAreaConstruida;
    private javax.swing.JLabel lblAreaTerreno;
    private javax.swing.JLabel lblContribuinte;
    private javax.swing.JLabel lblInscricaoImobiliaria;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblNome5;
    private javax.swing.JLabel lblNome6;
    private javax.swing.JLabel lblNome7;
    private javax.swing.JLabel lblPredios;
    private javax.swing.JLabel lblSeta;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorVenal;
    private javax.swing.JTextField txtAreaConstruida;
    private javax.swing.JTextField txtAreaTerreno;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtInscricao;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtValorVenal;
    // End of variables declaration//GEN-END:variables
}
