/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.lancamento.view;
import br.com.ifba.lancamento.controller.LancamentoImpostoIController;
import br.com.ifba.lancamento.entity.LancamentoImposto;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.service.SessaoService;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class GerenciarLancamentos extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(GerenciarLancamentos.class);

    private final LancamentoImpostoIController lancamentoController;
    private final TelaCadastroLancamento telaCadastro;
    private final SessaoService sessaoService;
    
    /**
     * Creates new form GerenciarImoveis
     */
    public GerenciarLancamentos(LancamentoImpostoIController lancamentoController, TelaCadastroLancamento telaCadastro, SessaoService sessaoService) { 
        this.lancamentoController = lancamentoController;
        this.telaCadastro         = telaCadastro;
        this.sessaoService        = sessaoService; 
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTabela();
    }
    
    public void carregarTabela(){
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLancamentos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (LancamentoImposto l : lancamentoController.findByAtivoTrue()) {
 
                String inscricao;
                if (l.getImovel() != null) {
                    inscricao = l.getImovel().getInscricaoImobiliaria();
                } else {
                    inscricao = "-";
                }
 
                String imposto;
                if (l.getImposto() != null) {
                    imposto = l.getImposto().getDescricao();
                } else {
                    imposto = "-";
                }
 
                String valorFormatado = String.format("R$ %.2f", l.getValorTotalCalculado());
 
                modelo.addRow(new Object[]{
                    inscricao,
                    imposto,
                    String.valueOf(l.getAno()),
                    valorFormatado,
                    l.getId() 
                });
            }
        } catch (Exception e) {
            log.error("Erro ao carregar tabela de lançamentos: {}", e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLancamentos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Inscrição", "Imposto", "Ano", "Valor Total", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLancamentos);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar.png"))); // NOI18N
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        btnExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnEditar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblLancamentos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um lançamento na tabela para excluir.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id        = (Long)   tblLancamentos.getValueAt(linha, 4);
        String inscricao = (String) tblLancamentos.getValueAt(linha, 0);
 
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja inativar o lançamento do imóvel:\n\"" + inscricao + "\"?",
                "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                lancamentoController.delete(id);
                JOptionPane.showMessageDialog(this,
                        "Lançamento inativado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblLancamentos.clearSelection();
                carregarTabela();
            } catch (Exception ex) {
                log.error("Erro ao excluir lançamento ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tblLancamentos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um lançamento na tabela para editar.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long id = (Long) tblLancamentos.getValueAt(linha, 4);
        LancamentoImposto lancamento = lancamentoController.findById(id);
 
        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(lancamento);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();
 
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
 
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblLancamentos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (LancamentoImposto l : lancamentoController.findByAtivoTrue()) {
 
                String inscricao;
                if (l.getImovel() != null) {
                    inscricao = l.getImovel().getInscricaoImobiliaria();
                } else {
                    inscricao = "";
                }
 
                String imposto;
                if (l.getImposto() != null) {
                    imposto = l.getImposto().getDescricao();
                } else {
                    imposto = "";
                }
 
                String ano = String.valueOf(l.getAno());
 
                boolean correspondeInscricao = inscricao.toLowerCase().contains(texto.toLowerCase());
                boolean correspondeImposto   = imposto.toLowerCase().contains(texto.toLowerCase());
                boolean correspondeAno       = ano.contains(texto);
 
                if (correspondeInscricao || correspondeImposto || correspondeAno) {
                    modelo.addRow(new Object[]{
                        inscricao,
                        imposto,
                        ano,
                        String.format("R$ %.2f", l.getValorTotalCalculado()),
                        l.getId()
                    });
                }
            }
 
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum lançamento encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }
 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            Usuario logado = sessaoService.getUsuarioLogado();
            
            // Se NÃO for ADMIN, o botão de inativar/excluir fica cinza (desabilitado)
            if (logado != null && !logado.getNivelAcesso().equals("ADMIN")) {
                btnExcluir.setEnabled(false);
                btnExcluir.setToolTipText("Apenas administradores podem inativar lançamentos.");
            } else {
                btnExcluir.setEnabled(true);
            }
        }
        super.setVisible(visible);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLancamentos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
