/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.lancamento.view;

import br.com.ifba.imovel.controller.ImovelIController;
import br.com.ifba.imovel.entity.Imovel;
import br.com.ifba.imposto.view.*;
import br.com.ifba.imposto.controller.ImpostoIController;
import br.com.ifba.imposto.entity.Imposto;
import br.com.ifba.imposto.entity.ImpostoIPTU;
import br.com.ifba.lancamento.controller.LancamentoImpostoIController;
import br.com.ifba.lancamento.entity.LancamentoImposto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaCadastroLancamento extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaCadastroLancamento.class);
    private GerenciarLancamentos telaPrincipal;
    private Long   idEmEdicao = null;
    private String modo       = "SALVAR";
 
    private final LancamentoImpostoIController lancamentoController;
    private final ImovelIController            imovelController;
    private final ImpostoIController           impostoController;
 
    private List<Imovel>  listaImoveis  = new ArrayList<>();
    private List<Imposto> listaImpostos = new ArrayList<>();
    /**
     * Creates new form TelaCadastroIPTU
     */
    public TelaCadastroLancamento(LancamentoImpostoIController lancamentoController, ImovelIController imovelController, ImpostoIController impostoController) {
        this.lancamentoController = lancamentoController;
        this.imovelController     = imovelController;
        this.impostoController    = impostoController;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    public void setModo(String modo, Long id, GerenciarLancamentos principal) {
        this.modo          = modo;
        this.idEmEdicao    = id;
        this.telaPrincipal = principal;
 
        if (modo.equals("EDITAR")) {
            lblTitulo.setText("EDITAR LANÇAMENTO");
        } else {
            lblTitulo.setText("NOVO LANÇAMENTO");
        }
 
        carregarCombos();
 
        if (modo.equals("SALVAR")) {
            limparCampos();
            cmbImovel.setEnabled(true);
            txtParcelas.setEnabled(true);
        } else {
            cmbImovel.setEnabled(false);
            txtParcelas.setEnabled(false);
            txtParcelas.setText("—");
        }
    }
    
    public void preencherCampos(LancamentoImposto lancamento) {
        if (lancamento.getImovel() != null) {
            for (int i = 0; i < listaImoveis.size(); i++) {
                if (listaImoveis.get(i).getId().equals(lancamento.getImovel().getId())) {
                    cmbImovel.setSelectedIndex(i);
                    break;
                }
            }
        }
 
        if (lancamento.getImposto() != null) {
            for (int i = 0; i < listaImpostos.size(); i++) {
                if (listaImpostos.get(i).getId().equals(lancamento.getImposto().getId())) {
                    cmbImposto.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    
    private void limparCampos() {
        if (cmbImovel.getItemCount() > 0) {
            cmbImovel.setSelectedIndex(0);
        }
        if (cmbImposto.getItemCount() > 0) {
            cmbImposto.setSelectedIndex(0);
        }
        txtParcelas.setText("1");
    }
    
    private void carregarCombos() {
        listaImoveis = imovelController.findByAtivoTrue();
        cmbImovel.removeAllItems();
 
        for (Imovel i : listaImoveis) {
            String bairro;
            if (i.getEndereco() != null) {
                bairro = i.getEndereco().getBairro();
            } else {
                bairro = "—";
            }
            cmbImovel.addItem(i.getInscricaoImobiliaria() + " | " + bairro);
        }
 
        listaImpostos = impostoController.findByAtivoTrue();
        cmbImposto.removeAllItems();
 
        for (Imposto imp : listaImpostos) {
            cmbImposto.addItem(imp.getDescricao() + " (" + imp.getAnoExercicio() + ")");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblImovel = new javax.swing.JLabel();
        lblImposto = new javax.swing.JLabel();
        lblParcelas = new javax.swing.JLabel();
        txtParcelas = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbImposto = new javax.swing.JComboBox<>();
        cmbImovel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo Automático da :) tela");

        lblImovel.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblImovel.setText("Imovel:");

        lblImposto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblImposto.setText("Imposto:");

        lblParcelas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblParcelas.setText("N° Parcelas:");

        lblBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pasta-de-documentos.png"))); // NOI18N

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salve-.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        cmbImposto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblParcelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtParcelas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblImposto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbImposto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)
                        .addComponent(lblBanco)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImovel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImovel)
                            .addComponent(cmbImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImposto)
                            .addComponent(cmbImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblParcelas)
                            .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(lblBanco)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            if (listaImoveis.isEmpty() || cmbImovel.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this,
                        "Selecione um imóvel.",
                        "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
                return;
            }
 
            if (listaImpostos.isEmpty() || cmbImposto.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this,
                        "Selecione um imposto.",
                        "Campo obrigatório", JOptionPane.WARNING_MESSAGE);
                return;
            }
 
            Imovel  imovelSelecionado  = listaImoveis.get(cmbImovel.getSelectedIndex());
            Imposto impostoSelecionado = listaImpostos.get(cmbImposto.getSelectedIndex());
 
            LancamentoImposto lancamento = new LancamentoImposto();
            lancamento.setImovel(imovelSelecionado);
            lancamento.setImposto(impostoSelecionado);
 
            if (modo.equals("EDITAR") && idEmEdicao != null) {
                lancamentoController.update(idEmEdicao, lancamento);
                JOptionPane.showMessageDialog(this, "Lançamento atualizado com sucesso!");
            } else {
                int parcelas = Integer.parseInt(txtParcelas.getText().trim());
                lancamentoController.save(lancamento, parcelas);
                JOptionPane.showMessageDialog(this,
                        "Lançamento registrado!\nBoletos gerados automaticamente.");
            }
 
            limparCampos();
            telaPrincipal.carregarTabela();
            this.dispose();
 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "O número de parcelas deve ser um inteiro (ex: 1, 3, 12).",
                    "Valor inválido", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            log.warn("Erro ao salvar lançamento: {}", ex.getMessage());
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro ao Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbImovel;
    private javax.swing.JComboBox<String> cmbImposto;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblImovel;
    private javax.swing.JLabel lblImposto;
    private javax.swing.JLabel lblParcelas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtParcelas;
    // End of variables declaration//GEN-END:variables
}
