/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;

import br.com.ifba.usuario.controller.UsuarioIController;
import br.com.ifba.usuario.entity.Usuario;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduardo
 */
@Component
public class GerenciarUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarUsuarios.class.getName());
    private final UsuarioIController usuarioController;
    private final TelaCadastroUsuario telaCadastro;

 
    public GerenciarUsuarios(UsuarioIController usuarioController, TelaCadastroUsuario telaCadastro) {
        this.usuarioController = usuarioController;
        this.telaCadastro = telaCadastro;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
        carregarTabela();
    }
    
    public void carregarTabela() {
    javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
    modelo.setRowCount(0);

    for (Usuario u : usuarioController.listarTodos()) {
        modelo.addRow(new Object[]{u.getNome(), u.getLogin(), u.getNivelAcesso(), u.getId()});
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnAdicionar.setBackground(new java.awt.Color(51, 51, 255));
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Login", "Senha", "Nivel de acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
            // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblUsuarios.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário para excluir.");
            return;
        }
    
        // 2. Coleta os dados exatos da linha selecionada (ID e Nível de Acesso)
        Long id = (Long) tblUsuarios.getValueAt(linha, 3);
        String nivelAlvo = (String) tblUsuarios.getValueAt(linha, 2); 
    
        // 3. Pega quem está logado no sistema neste exato momento
        Usuario logado = TelaLogin.usuarioLogado;

        // 4. Bateria de Regras de Segurança da Interface
        if (logado != null) {
            // REGRA A: Funcionário simples não deleta Admin
            if (!logado.getNivelAcesso().equals("ADMIN") && nivelAlvo.equals("ADMIN")) {
                JOptionPane.showMessageDialog(this, 
                    "Acesso Negado: Você não tem permissão para excluir um Administrador.", 
                    "Erro de Permissão", JOptionPane.ERROR_MESSAGE);
                return; // Para a execução do código aqui
            }

            // REGRA B: Ninguém pode se auto-excluir (Prevenção de inativação da sessão)
            if (id.equals(logado.getId())) {
                JOptionPane.showMessageDialog(this, 
                    "Acesso Negado: Você não pode excluir sua própria conta enquanto estiver logado no sistema.", 
                    "Ação Bloqueada", JOptionPane.WARNING_MESSAGE);
                return; // Para a execução do código aqui
            }
        }

        // 5. Se sobreviveu às regras de segurança, pede a confirmação final
        int confirm = JOptionPane.showConfirmDialog(
            this, "Tem certeza que deseja excluir permanentemente o usuário selecionado?", 
            "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION
        );
    
        // 6. Envia o comando para o Controller / Banco de Dados
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                usuarioController.deletar(id); // O seu Service ainda vai validar se não é a conta "admin"
                JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
            
                // Limpa o "fantasma" do clique na tabela e recarrega os dados
                tblUsuarios.clearSelection(); 
                carregarTabela();
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int linha = tblUsuarios.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário para editar.");
            return;
        }
        String nome   = (String) tblUsuarios.getValueAt(linha, 0);
        String login  = (String) tblUsuarios.getValueAt(linha, 1);
        String nivel  = (String) tblUsuarios.getValueAt(linha, 2);
        Long id       = (Long)   tblUsuarios.getValueAt(linha, 3);

        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(nome, login, nivel);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0);
        try {
            usuarioController.listarTodos().stream()
                .filter(u -> u.getNome().toLowerCase().contains(texto.toLowerCase())
                          || u.getLogin().toLowerCase().contains(texto.toLowerCase()))
                .forEach(u -> modelo.addRow(new Object[]{
                    u.getNome(), u.getLogin(), u.getNivelAcesso(), u.getId()
                }));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
