/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;

import br.com.ifba.usuario.controller.UsuarioIController;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.service.SessaoService;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduardo
 */
@Component
public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private final UsuarioIController usuarioController;
    private GerenciarUsuarios telaPrincipal;
    private Long idEmEdicao = null;
    private String modo = "SALVAR";
    private final SessaoService sessaoService;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName());

    /**
     * Creates new form TelaCadastroCurso
     */    
    public TelaCadastroUsuario(UsuarioIController usuarioController, SessaoService sessaoService) {
    this.usuarioController = usuarioController;
    this.sessaoService = sessaoService; // Adicionado
    this.setResizable(false);
    this.setLocationRelativeTo(null);
    initComponents();
}
    
    public void setModo(String modo, Long id, GerenciarUsuarios principal) {
        this.modo = modo;
        this.idEmEdicao = id;
        this.telaPrincipal = principal;
        lblTitulo.setText(modo.equals("EDITAR") ? "EDITAR USUÁRIO" : "CADASTRAR USUÁRIO");
        if (modo.equals("SALVAR")) limparCampos();
        
        configurarPermissoesDeTela();
    }
    
    private void configurarPermissoesDeTela() {
        Usuario logado = sessaoService.getUsuarioLogado();
    
        //Se NÃO for admin, ele nunca pode mexer no ComboBox de nível de acesso
        if (!logado.getNivelAcesso().equals("ADMIN")) {
            cmbNivel.setEnabled(false); 
        } else {
            cmbNivel.setEnabled(true);
        }
    
        // Se o usuário estiver editando a SI MESMO 
        if (modo.equals("EDITAR") && idEmEdicao.equals(logado.getId())) {
            // Bloqueia tudo, menos a senha
            txtNome.setEnabled(false);
            txtLogin.setEnabled(false);
            cmbNivel.setEnabled(false); // Reforça o bloqueio do cargo
        } else {
            // Se for um Admin editando outra pessoa, libera os textos
            txtNome.setEnabled(true);
            txtLogin.setEnabled(true);
        }
    }
    private void limparCampos() {
        txtNome.setText("");
        txtLogin.setText("");
        pswSenha.setText("");
        cmbNivel.setSelectedIndex(0);
    }
    
    public void preencherCampos(String nome, String login, String nivel) {
        txtNome.setText(nome);
        txtLogin.setText(login);
        cmbNivel.setSelectedItem(nivel);
        
        // O campo de palavra-passe deve ficar limpo por questões de segurança.
        // O utilizador só preenche este campo se realmente quiser alterar a palavra-passe.
        pswSenha.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblNivel = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        pswSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblNome.setText("Nome:");

        lblDescricao.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblDescricao.setText("Login:");

        lblSenha.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo Automático haha");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        txtLogin.addActionListener(this::txtLoginActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salve-.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        lblNivel.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        lblNivel.setText("Nivel de Acesso:");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "FISCAL", "ATENDENTE" }));
        cmbNivel.addActionListener(this::cmbNivelActionPerformed);

        pswSenha.addActionListener(this::pswSenhaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNivel)
                                .addGap(18, 18, 18)
                                .addComponent(cmbNivel, 0, 366, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pswSenha))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDescricao)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin)
                            .addComponent(txtNome))))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Criamos um objeto apenas para agrupar os dados da tela
        Usuario dadosFormulario = new Usuario();
        dadosFormulario.setNome(txtNome.getText());
        dadosFormulario.setLogin(txtLogin.getText());
        dadosFormulario.setSenha(new String(pswSenha.getPassword()));
        dadosFormulario.setNivelAcesso((String) cmbNivel.getSelectedItem());

        if (modo.equals("EDITAR") && idEmEdicao != null) {
            // 2. Passamos o ID de controle e o pacote de dados para o controller
            usuarioController.update(idEmEdicao, dadosFormulario);
            JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
        } else {
            // O cadastro do zero continua igual
            usuarioController.save(dadosFormulario);
            JOptionPane.showMessageDialog(this, "Usuário salvo!");
        }

        limparCampos();
        telaPrincipal.carregarTabela();
        this.dispose();

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNivelActionPerformed

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
