/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;

import static br.com.ifba.Application.context;
import br.com.ifba.contribuinte.view.GerenciarContribuintes;
import br.com.ifba.usuario.service.SessaoService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaMenuPrincipal extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaMenuPrincipal.class);    private final GerenciarUsuarios telaGerenciarUsuarios;
    private final SessaoService sessaoService;
    private final GerenciarContribuintes telaGerenciarContribuintes;
    /**
     * Creates new form TelaMenuPrincipal
     */

    //Construtor pika
    public TelaMenuPrincipal(GerenciarUsuarios telaGerenciarUsuarios, GerenciarContribuintes telaGerenciarContribuintes, SessaoService sessaoService) {
        this.telaGerenciarUsuarios     = telaGerenciarUsuarios;
        this.telaGerenciarContribuintes = telaGerenciarContribuintes; // ← adicionar
        this.sessaoService             = sessaoService;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadUsuario = new javax.swing.JMenuItem();
        mnuCadContribuinte = new javax.swing.JMenuItem();
        mnuImovel = new javax.swing.JMenuItem();
        mnuTributos = new javax.swing.JMenu();
        mnuEmissao = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuSistema.setText("Sistema");

        mnuSair.setText("Sair");
        mnuSair.addActionListener(this::mnuSairActionPerformed);
        mnuSistema.add(mnuSair);

        jMenuBar1.add(mnuSistema);

        mnuCadastros.setText("Cadastros");

        mnuCadUsuario.setText("Gerenciar Usuarios");
        mnuCadUsuario.addActionListener(this::mnuCadUsuarioActionPerformed);
        mnuCadastros.add(mnuCadUsuario);

        mnuCadContribuinte.setText("Gerenciar Contribuintes");
        mnuCadContribuinte.addActionListener(this::mnuCadContribuinteActionPerformed);
        mnuCadastros.add(mnuCadContribuinte);

        mnuImovel.setText("Gerenciar Imóveis");
        mnuCadastros.add(mnuImovel);

        jMenuBar1.add(mnuCadastros);

        mnuTributos.setText("Tributos");

        mnuEmissao.setText("Emissão de Guias");
        mnuTributos.add(mnuEmissao);

        mnuConsulta.setText("Consulta Débitos");
        mnuTributos.add(mnuConsulta);

        jMenuBar1.add(mnuTributos);

        mnuAjuda.setText("Ajuda");

        mnuSobre.setText("Sobre");
        mnuAjuda.add(mnuSobre);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        sessaoService.encerrarSessao();
        // 2) Reabre a TelaLogin buscando do contexto do Spring
        TelaLogin telaLogin = context.getBean(TelaLogin.class);
        telaLogin.setVisible(true);
        // 3) Fecha a tela atual do Menu Principal
        this.dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadUsuarioActionPerformed
        // TODO add your handling code here:
            telaGerenciarUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuCadUsuarioActionPerformed

    private void mnuCadContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadContribuinteActionPerformed
        // TODO add your handling code here:
        telaGerenciarContribuintes.carregarTabela(); // garante dados atualizadissimos já quando abre
        telaGerenciarContribuintes.setVisible(true);
    }//GEN-LAST:event_mnuCadContribuinteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuCadContribuinte;
    private javax.swing.JMenuItem mnuCadUsuario;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuEmissao;
    private javax.swing.JMenuItem mnuImovel;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenu mnuTributos;
    // End of variables declaration//GEN-END:variables
}
