/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.usuario.view;

import static br.com.ifba.Application.context;
import br.com.ifba.boleto.view.GerenciarBoletos;
import br.com.ifba.contribuinte.view.GerenciarContribuintes;
import br.com.ifba.imovel.view.GerenciarImoveis;
import br.com.ifba.imposto.view.GerenciarImpostos;
import br.com.ifba.lancamento.view.GerenciarLancamentos;
import br.com.ifba.pagamento.view.GerenciarPagamentos;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.service.SessaoService;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaMenuPrincipal extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaMenuPrincipal.class);
    private final GerenciarUsuarios telaGerenciarUsuarios;
    private final SessaoService sessaoService;
    private final GerenciarContribuintes telaGerenciarContribuintes;
    private final GerenciarImoveis telaGerenciarImoveis;
    private final GerenciarImpostos  telaGerenciarImpostos; 
    private final GerenciarLancamentos telaGerenciarLancamentos;
    private final GerenciarBoletos telaGerenciarBoletos;
    private final GerenciarPagamentos telaGerenciarPagamentos;
    /**
     * Creates new form TelaMenuPrincipal
     */

    //Construtor pika
    public TelaMenuPrincipal(GerenciarUsuarios telaGerenciarUsuarios, 
            GerenciarContribuintes telaGerenciarContribuintes, 
            SessaoService sessaoService, 
            GerenciarImoveis telaGerenciarImoveis, 
            GerenciarImpostos telaGerenciarImpostos,
            GerenciarLancamentos telaGerenciarLancamentos,
            GerenciarBoletos telaGerenciarBoletos,
            GerenciarPagamentos telaGerenciarPagamentos) {
        
        this.telaGerenciarUsuarios = telaGerenciarUsuarios;
        this.telaGerenciarContribuintes = telaGerenciarContribuintes;
        this.telaGerenciarImoveis = telaGerenciarImoveis;
        this.telaGerenciarImpostos = telaGerenciarImpostos;
        this.sessaoService = sessaoService;
        this.telaGerenciarLancamentos = telaGerenciarLancamentos;
        this.telaGerenciarBoletos = telaGerenciarBoletos;
        this.telaGerenciarPagamentos = telaGerenciarPagamentos;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGerenciamentoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadUsuario = new javax.swing.JMenuItem();
        mnuCadContribuinte = new javax.swing.JMenuItem();
        mnuImovel = new javax.swing.JMenuItem();
        mnuTributos = new javax.swing.JMenu();
        mnuEmissao = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        mnuGerenciarImpostos = new javax.swing.JMenuItem();
        mnuGerenciarPagamentos = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGerenciamentoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/equipe.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setText("Bem vindo(a)");

        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTitulo.setText("Sistema de Gerenciamento de Tributos");

        mnuSistema.setText("Sistema");

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(this::mnuSairActionPerformed);
        mnuSistema.add(mnuSair);

        jMenuBar1.add(mnuSistema);

        mnuCadastros.setText("Cadastros");

        mnuCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gerenciamento-de-usuarios.png"))); // NOI18N
        mnuCadUsuario.setText("Gerenciar Usuarios");
        mnuCadUsuario.addActionListener(this::mnuCadUsuarioActionPerformed);
        mnuCadastros.add(mnuCadUsuario);

        mnuCadContribuinte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gerenciamento.png"))); // NOI18N
        mnuCadContribuinte.setText("Gerenciar Contribuintes");
        mnuCadContribuinte.addActionListener(this::mnuCadContribuinteActionPerformed);
        mnuCadastros.add(mnuCadContribuinte);

        mnuImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa.png"))); // NOI18N
        mnuImovel.setText("Gerenciar Imóveis");
        mnuImovel.addActionListener(this::mnuImovelActionPerformed);
        mnuCadastros.add(mnuImovel);

        jMenuBar1.add(mnuCadastros);

        mnuTributos.setText("Tributos");

        mnuEmissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/universidade.png"))); // NOI18N
        mnuEmissao.setText("Emissão de Guias");
        mnuEmissao.addActionListener(this::mnuEmissaoActionPerformed);
        mnuTributos.add(mnuEmissao);

        mnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-debit-64.png"))); // NOI18N
        mnuConsulta.setText("Consulta Débitos");
        mnuConsulta.addActionListener(this::mnuConsultaActionPerformed);
        mnuTributos.add(mnuConsulta);

        mnuGerenciarImpostos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dinheiro_1.png"))); // NOI18N
        mnuGerenciarImpostos.setText("GerenciarImpostos");
        mnuGerenciarImpostos.addActionListener(this::mnuGerenciarImpostosActionPerformed);
        mnuTributos.add(mnuGerenciarImpostos);

        mnuGerenciarPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pagamento.png"))); // NOI18N
        mnuGerenciarPagamentos.setText("Realizar Pagamentos");
        mnuGerenciarPagamentos.addActionListener(this::mnuGerenciarPagamentosActionPerformed);
        mnuTributos.add(mnuGerenciarPagamentos);

        jMenuBar1.add(mnuTributos);

        mnuAjuda.setText("Ajuda");

        mnuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-question-mark-50.png"))); // NOI18N
        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(this::mnuSobreActionPerformed);
        mnuAjuda.add(mnuSobre);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 444, Short.MAX_VALUE)
                .addComponent(lblGerenciamentoImg))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblSubTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGerenciamentoImg)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        sessaoService.encerrarSessao();
        // 2) Reabre a TelaLogin buscando do contexto do Spring
        TelaLogin telaLogin = context.getBean(TelaLogin.class);
        telaLogin.setVisible(true);
        // 3) Fecha a tela atual do Menu Principal
        this.dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadUsuarioActionPerformed
        // TODO add your handling code here:
        telaGerenciarUsuarios.carregarTabela();
        telaGerenciarUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuCadUsuarioActionPerformed

    private void mnuCadContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadContribuinteActionPerformed
        // TODO add your handling code here:
        telaGerenciarContribuintes.carregarTabela(); // garante dados atualizadissimos já quando abre
        telaGerenciarContribuintes.setVisible(true);
    }//GEN-LAST:event_mnuCadContribuinteActionPerformed

    private void mnuImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImovelActionPerformed
        // TODO add your handling code here:
        telaGerenciarImoveis.carregarTabela();
        telaGerenciarImoveis.setVisible(true);
    }//GEN-LAST:event_mnuImovelActionPerformed

    private void mnuGerenciarImpostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarImpostosActionPerformed
        // TODO add your handling code here:
        telaGerenciarImpostos.carregarTabela();
        telaGerenciarImpostos.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarImpostosActionPerformed

    private void mnuEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmissaoActionPerformed
        // TODO add your handling code here:
        telaGerenciarLancamentos.carregarTabela();
        telaGerenciarLancamentos.setVisible(true);
    }//GEN-LAST:event_mnuEmissaoActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        // TODO add your handling code here:
        telaGerenciarBoletos.carregarTabela();
        telaGerenciarBoletos.setVisible(true);
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void mnuGerenciarPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarPagamentosActionPerformed
        // TODO add your handling code here:
        telaGerenciarPagamentos.carregarTabela();
        telaGerenciarPagamentos.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarPagamentosActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        // TODO add your handling code here:
        String mensagem = "Sistema de Gerenciamento de Tributos\n"
                        + "Versão: 1.0\n\n"
                        + "Desenvolvido por: Eduardo Nascimento\n"
                        + "Instituto Federal da Bahia (IFBA) - Campus Irecê\n"
                        + "Curso: Análise e Desenvolvimento de Sistemas\n\n"
                        + "Sistema desenvolvido com Spring Boot e Java Swing.\n"
                        + "© 2026 Todos os direitos reservados.";
        
        JOptionPane.showMessageDialog(this, 
                                      mensagem, 
                                      "Sobre o Sistema", 
                                      JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setVisible(boolean visible) {
        if (visible) {
            configurarMenuPorPerfil();
        }
        super.setVisible(visible);
    }

    private void configurarMenuPorPerfil() {
        Usuario logado = sessaoService.getUsuarioLogado();
        
        if (logado == null) {
            // Se ninguém logou, esconde as opções principais por segurança
            mnuCadastros.setVisible(false);
            mnuTributos.setVisible(false);
            return;
        }

        //deixa todos menus visiveis
        mnuCadastros.setVisible(true);
        mnuTributos.setVisible(true);
        mnuCadUsuario.setVisible(true);
        mnuCadContribuinte.setVisible(true);
        mnuImovel.setVisible(true);
        mnuEmissao.setVisible(true);
        mnuConsulta.setVisible(true);
        mnuGerenciarImpostos.setVisible(true);
        mnuGerenciarPagamentos.setVisible(true);

        // Ocultamos o que não é da alçada do cargo
        String nivel = logado.getNivelAcesso();

        if (nivel.equals("FISCAL")) {
            // O Fiscal não mexe com usuários nem com o caixa (pagamentos)
            mnuCadUsuario.setVisible(false);
            mnuGerenciarPagamentos.setVisible(false);
            
        } else if (nivel.equals("ATENDENTE")) {
            // O Atendente atende o público e recebe pagamentos. Não altera as bases do IPTU.
            mnuCadUsuario.setVisible(false);
            mnuImovel.setVisible(false);
            mnuEmissao.setVisible(false);
            mnuGerenciarImpostos.setVisible(false);
            
        } else if (nivel.equals("ADMIN")) {
            // O Admin vê absolutamente tudo. Não precisamos ocultar nada.
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblGerenciamentoImg;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuCadContribuinte;
    private javax.swing.JMenuItem mnuCadUsuario;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenuItem mnuEmissao;
    private javax.swing.JMenuItem mnuGerenciarImpostos;
    private javax.swing.JMenuItem mnuGerenciarPagamentos;
    private javax.swing.JMenuItem mnuImovel;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenu mnuTributos;
    // End of variables declaration//GEN-END:variables
}
