spring.application.name=prg03sistematributario
spring.datasource.url=jdbc:postgresql://db.ishrugobupdymzzbhqmt.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]
spring.datasource.username=postgres
spring.datasource.password=D1GyjhuasWaE5D1J
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update