/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.boleto.view;

import br.com.ifba.boleto.controller.BoletosPrefeituraIController;
import br.com.ifba.boleto.entity.BoletosPrefeitura;
import br.com.ifba.pagamento.controller.PagamentoIController;
import br.com.ifba.usuario.service.SessaoService;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class GerenciarBoletos extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(GerenciarBoletos.class);
    private static final DateTimeFormatter FMT_DATA = DateTimeFormatter.ofPattern("dd/MM/yyyy");
 
    private final BoletosPrefeituraIController boletoController;
    private final PagamentoIController         pagamentoController;
    private final SessaoService                sessaoService;
    
    /**
     * Creates new form GerenciarImoveis
     */
    public GerenciarBoletos(BoletosPrefeituraIController boletoController, PagamentoIController pagamentoController, SessaoService sessaoService) {
        this.boletoController    = boletoController;
        this.pagamentoController = pagamentoController;
        this.sessaoService       = sessaoService;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTabela();
    }
    
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblBoletos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (BoletosPrefeitura b : boletoController.findByAtivoTrue()) {
 
                // Atualiza automaticamente boletos vencidos
                if (b.getStatus().equals("PENDENTE") && b.verificarVencimento()) {
                    boletoController.updateStatus(b.getId(), "VENCIDO");
                    b.setStatus("VENCIDO");
                }
 
                String vencimento;
                if (b.getDataVencimento() != null) {
                    vencimento = b.getDataVencimento().format(FMT_DATA);
                } else {
                    vencimento = "-";
                }
                
                String inscricao = "Não informada";
                if (b.getLancamentoImposto() != null && b.getLancamentoImposto().getImovel() != null) {
                    inscricao = b.getLancamentoImposto().getImovel().getInscricaoImobiliaria();
                }
 
                modelo.addRow(new Object[]{
                    inscricao,
                    b.getNumeroCodigoBarras(),  
                    String.format("R$ %.2f", b.getValorBoleto()),  
                    vencimento,                                   
                    b.getStatus(),                                 
                    b.getId()                                      
                });
            }
        } catch (Exception e) {
            log.error("Erro ao carregar tabela de boletos: {}", e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoletos = new javax.swing.JTable();
        btnPagar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Inscrição Imobiliária", "Código de barras", "Valor", "Vencimento", "Status", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBoletos);
        if (tblBoletos.getColumnModel().getColumnCount() > 0) {
            tblBoletos.getColumnModel().getColumn(0).setResizable(false);
            tblBoletos.getColumnModel().getColumn(1).setResizable(false);
            tblBoletos.getColumnModel().getColumn(2).setResizable(false);
            tblBoletos.getColumnModel().getColumn(3).setResizable(false);
            tblBoletos.getColumnModel().getColumn(4).setResizable(false);
            tblBoletos.getColumnModel().getColumn(5).setResizable(false);
        }

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dinheiro.png"))); // NOI18N
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        btnExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        int linha = tblBoletos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um boleto para registrar o pagamento.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   boletoId = (Long)   tblBoletos.getValueAt(linha, 5); 
        String status   = (String) tblBoletos.getValueAt(linha, 4); 
        String valor    = (String) tblBoletos.getValueAt(linha, 2);
 
        if (status.equals("PAGO")) {
            JOptionPane.showMessageDialog(this,
                    "Este boleto já foi pago.",
                    "Ação inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        if (status.equals("VENCIDO")) {
            int opcao = JOptionPane.showConfirmDialog(this,
                    "Este boleto está VENCIDO.\nDeseja registrar o pagamento mesmo assim?",
                    "Boleto Vencido", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
 
            if (opcao != JOptionPane.YES_OPTION) {
                return;
            }
        }
 
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Confirmar pagamento do boleto?\nValor: " + valor,
                "Confirmar Pagamento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                Long usuarioId = sessaoService.getUsuarioLogado().getId();
                pagamentoController.save(boletoId, usuarioId);
                JOptionPane.showMessageDialog(this,
                        "Pagamento registrado com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblBoletos.clearSelection();
                carregarTabela();
            } catch (Exception ex) {
                log.error("Erro ao registrar pagamento do boleto ID {}: {}", boletoId, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Erro ao Pagar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblBoletos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um boleto para excluir.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id        = (Long)   tblBoletos.getValueAt(linha, 5); // Agora é 5
        String inscricao = (String) tblBoletos.getValueAt(linha, 0);
 
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o boleto da inscrição:\n\"" + inscricao + "\"?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                boletoController.delete(id);
                JOptionPane.showMessageDialog(this,
                        "Boleto excluído com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblBoletos.clearSelection();
                carregarTabela();
            } catch (Exception ex) {
                log.error("Erro ao excluir boleto ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim().toLowerCase();
 
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
 
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblBoletos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (BoletosPrefeitura b : boletoController.findByAtivoTrue()) {
 
                String inscricao = "";
                if (b.getLancamentoImposto() != null && b.getLancamentoImposto().getImovel() != null) {
                    inscricao = b.getLancamentoImposto().getImovel().getInscricaoImobiliaria();
                }
                
                //  o filtro principal é a Inscrição Imobiliária
                boolean correspondeInscricao = inscricao.toLowerCase().contains(texto);
                boolean correspondeStatus = b.getStatus().toLowerCase().contains(texto);
 
                if (correspondeInscricao || correspondeStatus) {
                    String vencimento = (b.getDataVencimento() != null) ? b.getDataVencimento().format(FMT_DATA) : "-";
 
                    modelo.addRow(new Object[]{
                        inscricao,
                        b.getNumeroCodigoBarras(),
                        String.format("R$ %.2f", b.getValorBoleto()),
                        vencimento,
                        b.getStatus(),
                        b.getId()
                    });
                }
            }
 
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum boleto encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }
 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoletos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
