/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.contribuinte.view;

import br.com.ifba.contribuinte.controller.ContribuinteIController;
import br.com.ifba.contribuinte.entity.Contribuinte;
import br.com.ifba.usuario.entity.Usuario;
import br.com.ifba.usuario.service.SessaoService;
import java.util.List;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduardo
 */
@Component
public class GerenciarContribuintes extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(GerenciarContribuintes.class);
 
    private final ContribuinteIController contribuinteController;
    private final TelaCadastroContribuinte telaCadastro;
 
    public GerenciarContribuintes(ContribuinteIController contribuinteController,
                                   TelaCadastroContribuinte telaCadastro) {
        this.contribuinteController = contribuinteController;
        this.telaCadastro = telaCadastro;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTabela();
    }
    
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel modelo = 
            (javax.swing.table.DefaultTableModel) tblContribuintes.getModel();
        modelo.setRowCount(0);

        for (Contribuinte c : contribuinteController.findByAtivoTrue()) {
            modelo.addRow(new Object[]{c.getNome(), c.getCpfCnpj(), c.getTelefone(), c.getEmail(), c.getId()});
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContribuintes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnAdicionar.setBackground(new java.awt.Color(204, 204, 204));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editing.png"))); // NOI18N
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash.png"))); // NOI18N
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        tblContribuintes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF/CNPJ", "Telefone", "E-Mail", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContribuintes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(372, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
            // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblContribuintes.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um contribuinte na tabela para excluir.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id   = (Long)   tblContribuintes.getValueAt(linha, 4);
        String nome = (String) tblContribuintes.getValueAt(linha, 0);
 
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o contribuinte:\n\"" + nome + "\"?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                contribuinteController.delete(id);
                JOptionPane.showMessageDialog(this,
                        "Contribuinte excluído com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblContribuintes.clearSelection();
                carregarTabela();
 
            } catch (Exception ex) {
                log.error("Erro ao excluir contribuinte ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int linha = tblContribuintes.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um contribuinte na tabela para editar.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long id = (Long) tblContribuintes.getValueAt(linha, 4);
 
        // Busca o objeto completo para obter também os dados de endereço,
        // que não estão expostos como colunas da tabela
        Contribuinte contribuinte = contribuinteController.findById(id);
 
        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(contribuinte);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();
 
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
 
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblContribuintes.getModel();
        modelo.setRowCount(0);
 
        try {
            contribuinteController.findByAtivoTrue().stream()
                .filter(c ->
                    c.getNome().toLowerCase().contains(texto.toLowerCase()) ||
                    c.getCpfCnpj().contains(texto)
                )
                .forEach(c -> modelo.addRow(new Object[]{
                    c.getNome(), c.getCpfCnpj(), c.getTelefone(), c.getEmail(), c.getId()
                }));
 
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum contribuinte encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }
 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContribuintes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
