/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.contribuinte.view;

import br.com.ifba.contribuinte.controller.ContribuinteIController;
import br.com.ifba.usuario.entity.Usuario;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaCadastroContribuinte extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaCadastroContribuinte.class);
 
    private final ContribuinteIController contribuinteController;
 
    private GerenciarContribuintes telaPrincipal;
    private Long   idEmEdicao = null;
    private String modo       = "SALVAR";
 

    /**
     * Creates new form TelaCadastroContribuinte
     */
    public TelaCadastroContribuinte(ContribuinteIController contribuinteController) {
        this.contribuinteController = contribuinteController;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }
    
    public void setModo(String modo, Long id, GerenciarContribuintes principal) {
        this.modo       = modo;
        this.idEmEdicao = id;
        this.telaPrincipal = principal;
 
        lblTitulo.setText(modo.equals("EDITAR") ? "EDITAR CONTRIBUINTE" : "CADASTRAR CONTRIBUINTE");
 
        if (modo.equals("SALVAR")) {
            limparCampos();
        }
    }
    
    private void configurarPermissoesDeTela() {
        Usuario logado = sessaoService.getUsuarioLogado();
    
        //Se NÃO for admin, ele nunca pode mexer no ComboBox de nível de acesso
        if (!logado.getNivelAcesso().equals("ADMIN")) {
            cmbNivel.setEnabled(false); 
        } else {
            cmbNivel.setEnabled(true);
        }
    
        // Se o usuário estiver editando a SI MESMO 
        if (modo.equals("EDITAR") && idEmEdicao.equals(logado.getId())) {
            // Bloqueia tudo, menos a senha
            txtNome.setEnabled(false);
            txtLogin.setEnabled(false);
            cmbNivel.setEnabled(false); // Reforça o bloqueio do cargo
        } else {
            // Se for um Admin editando outra pessoa, libera os textos
            txtNome.setEnabled(true);
            txtLogin.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo Automático da segunda tela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroContribuinte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
