/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.imposto.view;

import br.com.ifba.imposto.controller.ImpostoIController;
import br.com.ifba.imposto.entity.Imposto;
import br.com.ifba.imposto.entity.ImpostoIPTU;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class GerenciarImpostos extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(GerenciarImpostos.class);
    private final ImpostoIController impostoController;
    private final TelaCadastroIptu telaCadastro;

    /**
     * Creates new form GerenciarImpostos
     */
    public GerenciarImpostos(ImpostoIController impostoController, TelaCadastroIptu telaCadastro) {
        this.impostoController = impostoController;
        this.telaCadastro = telaCadastro;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
        carregarTabela();
    }
    
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblImpostos.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        try {
            for (Imposto imposto : impostoController.findByAtivoTrue()) {
                
                // Variáveis STR (strings) para carregar a tabela
                String aliquotaTerrenoStr;
                String aliquotaConstrucaoStr;
                String tipoImposto;

                // Verifica, usando IF expandido, se o imposto que veio do banco é um IPTU
                if (imposto instanceof ImpostoIPTU) {
                    ImpostoIPTU iptu = (ImpostoIPTU) imposto;
                    aliquotaTerrenoStr = String.valueOf(iptu.getAliquotaTerreno());
                    aliquotaConstrucaoStr = String.valueOf(iptu.getAliquotaConstrucao());
                    tipoImposto = "IPTU";
                } else {
                    aliquotaTerrenoStr = "-";
                    aliquotaConstrucaoStr = "-";
                    tipoImposto = "Geral";
                }
                
                // Adiciona a linha na tabela (Lembre-se de configurar essas 6 colunas no Design do NetBeans!)
                modelo.addRow(new Object[]{
                    imposto.getDescricao(),
                    imposto.getAnoExercicio(),
                    tipoImposto,
                    aliquotaTerrenoStr,
                    aliquotaConstrucaoStr,
                    imposto.getId()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImpostos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluir.png"))); // NOI18N
        btnExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        btnEditar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblImpostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Descrição", "Ano de Exercicio", "Tipo", "Aliq. Terreno", "Aliq. Construção", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblImpostos);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar.png"))); // NOI18N
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tblImpostos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                "Selecione um imposto na tabela para excluir.",
                "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // O ID está na coluna 5, e a Descrição está na coluna 0
        Long id = (Long) tblImpostos.getValueAt(linha, 5);
        String descricao = (String) tblImpostos.getValueAt(linha, 0);

        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja excluir o imposto:\n\"" + descricao + "\"?",
            "Confirmar Exclusão",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                impostoController.delete(id); // Corrigido para impostoController
                JOptionPane.showMessageDialog(this,
                    "Imposto excluído com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblImpostos.clearSelection();
                carregarTabela();

            } catch (Exception ex) {
                log.error("Erro ao excluir imposto ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tblImpostos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                "Selecione um imposto na tabela para editar.",
                "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // O ID está na coluna 5
        Long id = (Long) tblImpostos.getValueAt(linha, 5);

        // Corrigido para buscar um Imposto através do impostoController
        Imposto imposto = impostoController.findById(id);

        telaCadastro.setModo("EDITAR", id, this);
        telaCadastro.preencherCampos(imposto);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim();

        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblImpostos.getModel();
        modelo.setRowCount(0);

        try {
            // Corrigido para usar impostoController e varrer Impostos
            for (Imposto imposto : impostoController.findByAtivoTrue()) {
                
                // Verifica se a descrição do imposto contém o texto buscado
                if (imposto.getDescricao().toLowerCase().contains(texto.toLowerCase())) {
                    
                    String aliquotaTerrenoStr;
                    String aliquotaConstrucaoStr;
                    String tipoImposto;

                    // IF expandido para verificar se é IPTU e extrair dados específicos
                    if (imposto instanceof ImpostoIPTU) {
                        ImpostoIPTU iptu = (ImpostoIPTU) imposto;
                        aliquotaTerrenoStr = String.valueOf(iptu.getAliquotaTerreno());
                        aliquotaConstrucaoStr = String.valueOf(iptu.getAliquotaConstrucao());
                        tipoImposto = "IPTU";
                    } else {
                        aliquotaTerrenoStr = "-";
                        aliquotaConstrucaoStr = "-";
                        tipoImposto = "Geral";
                    }

                    modelo.addRow(new Object[]{
                        imposto.getDescricao(),
                        imposto.getAnoExercicio(),
                        tipoImposto,
                        aliquotaTerrenoStr,
                        aliquotaConstrucaoStr,
                        imposto.getId()
                    });
                }
            }

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                    "Nenhum imposto encontrado para: \"" + texto + "\".",
                    "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Erro ao buscar: " + ex.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setModo("SALVAR", null, this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImpostos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
