/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.imposto.view;

import br.com.ifba.imposto.controller.ImpostoIController;
import br.com.ifba.imposto.entity.Imposto;
import br.com.ifba.imposto.entity.ImpostoIPTU;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class TelaCadastroIptu extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(TelaCadastroIptu.class); 
    private GerenciarImpostos telaPrincipal;
    private Long idEmEdicao = null;
    private String modo = "SALVAR";
    private final ImpostoIController impostoController;
    /**
     * Creates new form TelaCadastroIPTU
     */
    public TelaCadastroIptu(ImpostoIController impostoController) {
        this.impostoController = impostoController;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    public void setModo(String modo, Long id, GerenciarImpostos principal) {
        this.modo = modo;
        this.idEmEdicao = id;
        this.telaPrincipal = principal;
        
        if (modo.equals("EDITAR")) {
            lblTitulo.setText("EDITAR IPTU");
        } else {
            lblTitulo.setText("CADASTRAR IPTU");
        }
 
        if (modo.equals("SALVAR")) {
            limparCampos();
        }
    }
    
    public void preencherCampos(Imposto imposto) {
        txtDescricao.setText(imposto.getDescricao());
        txtAnoExercicio.setText(String.valueOf(imposto.getAnoExercicio()));
 
        // IF expandido: Só preenche as alíquotas se o imposto realmente for um IPTU
        if (imposto instanceof ImpostoIPTU) {
            ImpostoIPTU iptu = (ImpostoIPTU) imposto;
            txtAliquotaTerreno.setText(String.valueOf(iptu.getAliquotaTerreno()));
            txtAliquotaConstrucao.setText(String.valueOf(iptu.getAliquotaConstrucao()));
        } else {
            txtAliquotaTerreno.setText("");
            txtAliquotaConstrucao.setText("");
        }
    }
    
    private void limparCampos() {
        txtDescricao.setText("");
        txtAnoExercicio.setText("");
        txtAliquotaTerreno.setText("");
        txtAliquotaConstrucao.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescricaoImposto = new javax.swing.JLabel();
        lblAnoExercicio = new javax.swing.JLabel();
        lblAliquotaTerreno = new javax.swing.JLabel();
        lblAliquotaConstrucao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtAnoExercicio = new javax.swing.JTextField();
        txtAliquotaTerreno = new javax.swing.JTextField();
        txtAliquotaConstrucao = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo Automático da ??? tela");

        lblDescricaoImposto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDescricaoImposto.setText("Descrição do Imposto:");

        lblAnoExercicio.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblAnoExercicio.setText("Ano de exercício:");

        lblAliquotaTerreno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblAliquotaTerreno.setText("Aliquota do Terreno (%):");

        lblAliquotaConstrucao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblAliquotaConstrucao.setText("Aliquota da Construção (%):");

        txtAliquotaConstrucao.addActionListener(this::txtAliquotaConstrucaoActionPerformed);

        lblBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banco.png"))); // NOI18N

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salve-.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblAliquotaTerreno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAliquotaTerreno))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblAnoExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoExercicio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDescricaoImposto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAliquotaConstrucao)
                            .addComponent(btnSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAliquotaConstrucao)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar)))))
                .addGap(32, 32, 32)
                .addComponent(lblBanco)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricaoImposto)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnoExercicio)
                            .addComponent(txtAnoExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAliquotaTerreno)
                            .addComponent(txtAliquotaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAliquotaConstrucao)
                            .addComponent(txtAliquotaConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(lblBanco)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAliquotaConstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAliquotaConstrucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliquotaConstrucaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            ImpostoIPTU iptu = new ImpostoIPTU();
            iptu.setDescricao(txtDescricao.getText());
            iptu.setAnoExercicio(Integer.parseInt(txtAnoExercicio.getText().trim()));
            iptu.setAliquotaTerreno(Double.parseDouble(txtAliquotaTerreno.getText().replace(",", ".")));
            iptu.setAliquotaConstrucao(Double.parseDouble(txtAliquotaConstrucao.getText().replace(",", ".")));

            if (modo.equals("EDITAR") && idEmEdicao != null) {
                impostoController.update(idEmEdicao, iptu);
                JOptionPane.showMessageDialog(this, "IPTU atualizado com sucesso!");
            } else {
                impostoController.save(iptu);
                JOptionPane.showMessageDialog(this, "IPTU cadastrado com sucesso!");
            }

            limparCampos();
            telaPrincipal.carregarTabela();
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Ano e alíquotas devem ser números válidos.",
                "Valor inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            log.warn("Erro ao salvar IPTU: {}", ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao Salvar", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblAliquotaConstrucao;
    private javax.swing.JLabel lblAliquotaTerreno;
    private javax.swing.JLabel lblAnoExercicio;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblDescricaoImposto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAliquotaConstrucao;
    private javax.swing.JTextField txtAliquotaTerreno;
    private javax.swing.JTextField txtAnoExercicio;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
