/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.pagamento.view;

import br.com.ifba.pagamento.controller.PagamentoIController;
import br.com.ifba.pagamento.entity.Pagamento;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author eduar
 */
@Component
public class GerenciarPagamentos extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(GerenciarPagamentos.class);
    private static final DateTimeFormatter FMT_DATA = DateTimeFormatter.ofPattern("dd/MM/yyyy");
 
    private final PagamentoIController pagamentoController;
    
    /**
     * Creates new form GerenciarImoveis
     */
    public GerenciarPagamentos(PagamentoIController pagamentoController) {
        this.pagamentoController = pagamentoController;
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTabela();
    }
    
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblPagamentos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (Pagamento p : pagamentoController.findByAtivoTrue()) {
 
                String data;
                if (p.getDataPagamento() != null) {
                    data = p.getDataPagamento().format(FMT_DATA);
                } else {
                    data = "-";
                }
 
                String codigoBoleto;
                if (p.getBoletoPrefeitura() != null) {
                    codigoBoleto = p.getBoletoPrefeitura().getNumeroCodigoBarras();
                } else {
                    codigoBoleto = "-";
                }
 
                String nomeUsuario;
                if (p.getUsuario() != null) {
                    nomeUsuario = p.getUsuario().getNome();
                } else {
                    nomeUsuario = "-";
                }
                
                String inscricao = "Não informada";
                if (p.getBoletoPrefeitura() != null && 
                    p.getBoletoPrefeitura().getLancamentoImposto() != null && 
                    p.getBoletoPrefeitura().getLancamentoImposto().getImovel() != null) {
                    inscricao = p.getBoletoPrefeitura().getLancamentoImposto().getImovel().getInscricaoImobiliaria();
                }
 
                modelo.addRow(new Object[]{
                    inscricao,
                    data,                                        
                    String.format("R$ %.2f", p.getValorPago()),  
                    p.getStatus(),                                 
                    codigoBoleto,                                  
                    nomeUsuario,                                  
                    p.getId()                                      
                });
            }
        } catch (Exception e) {
            log.error("Erro ao carregar tabela de pagamentos: {}", e.getMessage());
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagamentos = new javax.swing.JTable();
        btnEstornar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Inscrição Imobiliária", "Data", "Valor Pago", "Status", "Boleto", "Operador", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPagamentos);

        btnEstornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restituicao.png"))); // NOI18N
        btnEstornar.setMaximumSize(new java.awt.Dimension(81, 23));
        btnEstornar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnEstornar.addActionListener(this::btnEstornarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstornar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(txtBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstornarActionPerformed
        // TODO add your handling code here:
        int linha = tblPagamentos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um pagamento para estornar.",
                    "Nenhuma seleção", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        Long   id        = (Long)   tblPagamentos.getValueAt(linha, 6); 
        String status    = (String) tblPagamentos.getValueAt(linha, 3); 
        String valor     = (String) tblPagamentos.getValueAt(linha, 2); 
        String inscricao = (String) tblPagamentos.getValueAt(linha, 0);
 
        if (status.equals("ESTORNADO")) {
            JOptionPane.showMessageDialog(this,
                    "Este pagamento já foi estornado.",
                    "Ação inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja ESTORNAR o pagamento de " + valor + " referente à inscrição " + inscricao + "?\n"
                + "O boleto voltará para o status PENDENTE.",
                "Confirmar Estorno", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
 
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                pagamentoController.delete(id);
                JOptionPane.showMessageDialog(this,
                        "Pagamento estornado com sucesso!\nO boleto voltou para PENDENTE.",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tblPagamentos.clearSelection();
                carregarTabela();
            } catch (Exception ex) {
                log.error("Erro ao estornar pagamento ID {}: {}", id, ex.getMessage());
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "Erro ao Estornar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEstornarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String texto = txtBuscar.getText().trim().toLowerCase();
 
        if (texto.isEmpty()) {
            carregarTabela();
            return;
        }
 
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblPagamentos.getModel();
        modelo.setRowCount(0);
 
        try {
            for (Pagamento p : pagamentoController.findByAtivoTrue()) {
 
                String nomeUsuario;
                if (p.getUsuario() != null) {
                    nomeUsuario = p.getUsuario().getNome();
                } else {
                    nomeUsuario = "";
                }
 
                String codBoleto;
                if (p.getBoletoPrefeitura() != null) {
                    codBoleto = p.getBoletoPrefeitura().getNumeroCodigoBarras();
                } else {
                    codBoleto = "";
                }
                
                String inscricao = "";
                if (p.getBoletoPrefeitura() != null && 
                    p.getBoletoPrefeitura().getLancamentoImposto() != null && 
                    p.getBoletoPrefeitura().getLancamentoImposto().getImovel() != null) {
                    inscricao = p.getBoletoPrefeitura().getLancamentoImposto().getImovel().getInscricaoImobiliaria();
                }
 
                boolean correspondeInscricao = inscricao.toLowerCase().contains(texto);
                boolean correspondeStatus  = p.getStatus().toLowerCase().contains(texto.toLowerCase());
                boolean correspondeUsuario = nomeUsuario.toLowerCase().contains(texto.toLowerCase());
                boolean correspondeBoleto  = codBoleto.toLowerCase().contains(texto.toLowerCase());
 
                if (correspondeInscricao || correspondeStatus || correspondeUsuario || correspondeBoleto) {
 
                    String data = (p.getDataPagamento() != null) ? p.getDataPagamento().format(FMT_DATA) : "-";
 
                    modelo.addRow(new Object[]{
                        inscricao,
                        data,
                        String.format("R$ %.2f", p.getValorPago()),
                        p.getStatus(),
                        codBoleto,
                        nomeUsuario,
                        p.getId()
                    });
                }
            }
 
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum pagamento encontrado para: \"" + texto + "\".",
                        "Busca sem resultado", JOptionPane.INFORMATION_MESSAGE);
            }
 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEstornar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagamentos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
